### ISSUE TITLE
[Planner] Numbers not displayed for lwn_ref

### ISSUE THREAD

**Issue by pelderson** [vmarc/knooppuntnet#143]
I have made a local walking node network (lwn and lwn_ref). 
https://knooppuntnet.nl/nl/analysis/network/12265258

The routes are fine and the routing works works, but the nodes have no numbers. 
https://knooppuntnet.nl/nl/map/hiking#kcart8-r1qq5-kcasgd

( Also, I see a problem with a tile there, refreshing with Control-F5 doesn't help)

**Comment by vmarc** [comment]
@pelderson thanks for reporting this problem

About the tile problem: can you provide more detail? Problem in "Achtergrond" or "Wandelen" or "Interesse punten" layer? Screenshot perhaps? If the problem is related to symbols being cut off at the tile borders, the problem may have been resolved by the new version that was put in production tonight.

**Comment by pelderson** [comment]
The tile problem is gone! Thanks.
Vr gr Peter Elderson


Op wo 3 feb. 2021 om 23:10 schreef vmarc <notifications@github.com>:

**Comment by vmarc** [comment]
Fixed in version 3.1.3

![map](https://user-images.githubusercontent.com/6596480/106938142-eb579f00-671e-11eb-912a-9d85fdeb8420.png)

**Comment by pelderson** [comment]
Most of the numbers now display fine, others are still not there! This
seems to be independent of zoom level. But some of these nodes are not
displayed at all at some zoom levels. (I can't be more specific because I
can't see the zoom level).

[image: image.png]
Vr gr Peter Elderson


Op do 4 feb. 2021 om 19:30 schreef vmarc <notifications@github.com>:
